server:
  port: 8085
spring:
  application:
    name: instalment-service
  datasource:
    url: jdbc:mysql://localhost:3306/carddatabase?useUnicode=true&characterEncoding=utf-8
    password: root
    username: tiger
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5      #设置心跳时间5秒
    lease-expiration-duration-in-seconds: 15  #设置过期时间15秒
mybatis:
  type-aliases-package: com.credit.pojo   #这个路径是interface下的实体类路径